### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by Nidev-lab** [Mendez-Gabriel/GoalKeepOrganizer-Frontend#87]
## Proceso

1. Ingrese a la pagina.
2. Llene el form de contacto.

## Resultado esperado

• Que no se permita colocar numero ni signos en el nombre del usuario.
• Que no se muestre ninguna información por consola. 

## Resultado actual

• Se permite colocar numero y signos en el nombre.
• Al enviar el form se muestra un mensaje por consola.

## Captura

![image](https://github.com/Mendez-Gabriel/GoalKeepOrganizer-Frontend/assets/53904695/b80bcd3f-f22f-41c2-9f19-23f9ee011262)
![image](https://github.com/Mendez-Gabriel/GoalKeepOrganizer-Frontend/assets/53904695/41ec9265-41a2-46ce-8e17-c747c8df6083)
![image](https://github.com/Mendez-Gabriel/GoalKeepOrganizer-Frontend/assets/53904695/905fbce8-f377-4e02-92f9-fb9ada535fd1)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas! Como estan? Chicos este problema aun persiste.

**Comment by Alejo-Duhart** [comment]
ahi se corrigio lose errores nico
